openapi: 3.0.4
info:
  title: Task API
  version: 1.0.0
servers:
- url: /
paths:
  /health:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Health"
          description: OK
      summary: Health check
      x-accepts:
      - application/json
components:
  schemas:
    Health:
      example:
        checkedAt: 2000-01-23T04:56:07.000+00:00
        version: version
        status: status
      properties:
        status:
          type: string
        version:
          type: string
        checkedAt:
          format: date-time
          type: string
      required:
      - checkedAt
      - status
      - version
      type: object
