import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./globals.css";
import Nav from "./ui/Nav";
import Container from '@mui/material/Container';
import CssBaseline from '@mui/material/CssBaseline';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <AppRouterCacheProvider>
          <Container>
            <Nav />
            {children}
          </Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
